sudo: false

services:
  - mysql
  - postgresql

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

notifications:
  email: false

install:
  - pip install -r requirements.txt

before_script:
  - sh -c "if [ '$DB' = "pgsql" ] ; then psql -c 'DROP DATABASE IF EXISTS test_database;' -U postgres ; fi"
  - sh -c "if [ '$DB' = "pgsql" ] ; then psql -c 'CREATE DATABASE test_database;' -U postgres ; fi"
  - sh -c "if [ '$DB' = "pgsql" ] ; then DATABASE_URL=postgres://postgres:@localhost:5432/test_database ; fi"
  - sh -c "if [ '$DB' = "mysql" ] ; then mysql -e 'CREATE DATABASE IF NOT EXISTS test_database;' ; fi"
  - sh -c "if [ '$DB' = "mysql" ] ; then DATABASE_URL=mysql://root:@localhost:3306/test_database ; fi"

script:
  - nosetests --with-coverage

after_success:
  - coveralls