sudo: false
language: python
python:
  - "2.7"
  - "3.4"

notifications:
  email: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy matplotlib nose
  - source activate env_name
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage

after_success:
  - coveralls --config_file .coveragec